[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink/contracts/src/"
]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[profile.ci]
verbosity = 4
fuzz_runs = 1000


[rpc_endpoints]
gnosis = "https://rpc.gnosischain.com"

[etherscan]
gnosis = {key = "{$ETHERSCAN_KEY}"}